version: "3.7"
services:
  php:
    image: agangji/php:7.4
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    volumes:
      - .:/var/www/html
    environment:
      - PHP_USER=$PHP_USER
      - PHP_GROUP=$PHP_GROUP
      - PHP_UID=$PHP_UID
      - PHP_GID=$PHP_GID
    command: ["precreate-user.sh", "php-fpm", "-F"]
